
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/it_assignment_5
    username: root
    password: leo@2002 

server:
  port: 8443
  ssl:
    enabled: true
    key-store: "/Users/adityaganguly/college/IT/assign5backend/localhost.p12"
    key-store-type: PKCS12
    key-store-password: changeit